name: Desert Aerial
favicon: null
layout_spectrum: 0.13143912004306912
typography_spectrum: 0.6749714994803071
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5309401054400951
  lightness: 0.8641489732544869
  saturation: 0.500452023698017
  rhythmicContrast: 0.8268383524846286
purpose: []
